# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /users/start2017/r0634161/Desktop/DDP/package/hw_project/project_hw/project_hw.cache/wt [current_project]
set_property parent.project_path /users/start2017/r0634161/Desktop/DDP/package/hw_project/project_hw/project_hw.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
read_verilog -library xil_defaultlib /users/start2017/r0634161/Desktop/DDP/package/hw_project/src/warmup/rtl/warmup1_verilog.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top warmup1_verilog -part xc7z010clg400-1


write_checkpoint -force -noxdef warmup1_verilog.dcp

catch { report_utilization -file warmup1_verilog_utilization_synth.rpt -pb warmup1_verilog_utilization_synth.pb }
