# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# TCL: /users/start2017/r0634161/Git/Project-DDP/actual_project/hw_project/tcl/constraints.tcl

# Block Designs: bd/rsa_project/rsa_project.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project || ORIG_REF_NAME==rsa_project}]

# IP: bd/rsa_project/ip/rsa_project_ARCACHE_0/rsa_project_ARCACHE_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_ARCACHE_0 || ORIG_REF_NAME==rsa_project_ARCACHE_0}]

# IP: bd/rsa_project/ip/rsa_project_ARUSER_0/rsa_project_ARUSER_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_ARUSER_0 || ORIG_REF_NAME==rsa_project_ARUSER_0}]

# IP: bd/rsa_project/ip/rsa_project_axi_dma_0_0/rsa_project_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_axi_dma_0_0 || ORIG_REF_NAME==rsa_project_axi_dma_0_0}]

# IP: bd/rsa_project/ip/rsa_project_axi_interconnect_0_0/rsa_project_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_axi_interconnect_0_0 || ORIG_REF_NAME==rsa_project_axi_interconnect_0_0}]

# IP: bd/rsa_project/ip/rsa_project_xbar_0/rsa_project_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_xbar_0 || ORIG_REF_NAME==rsa_project_xbar_0}]

# IP: bd/rsa_project/ip/rsa_project_axi_mem_intercon_0/rsa_project_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_axi_mem_intercon_0 || ORIG_REF_NAME==rsa_project_axi_mem_intercon_0}]

# IP: bd/rsa_project/ip/rsa_project_xbar_1/rsa_project_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_xbar_1 || ORIG_REF_NAME==rsa_project_xbar_1}]

# IP: bd/rsa_project/ip/rsa_project_axis_dwidth_converter_0_0/rsa_project_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_axis_dwidth_converter_0_0 || ORIG_REF_NAME==rsa_project_axis_dwidth_converter_0_0}]

# IP: bd/rsa_project/ip/rsa_project_axis_dwidth_converter_1_0/rsa_project_axis_dwidth_converter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_axis_dwidth_converter_1_0 || ORIG_REF_NAME==rsa_project_axis_dwidth_converter_1_0}]

# IP: bd/rsa_project/ip/rsa_project_command_interface_0_0/rsa_project_command_interface_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_command_interface_0_0 || ORIG_REF_NAME==rsa_project_command_interface_0_0}]

# IP: bd/rsa_project/ip/rsa_project_rst_processing_system7_0_100M_0/rsa_project_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==rsa_project_rst_processing_system7_0_100M_0}]

# IP: bd/rsa_project/ip/rsa_project_xlconstant_0_0/rsa_project_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_xlconstant_0_0 || ORIG_REF_NAME==rsa_project_xlconstant_0_0}]

# IP: bd/rsa_project/ip/rsa_project_processing_system7_0_0/rsa_project_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_processing_system7_0_0 || ORIG_REF_NAME==rsa_project_processing_system7_0_0}]

# IP: bd/rsa_project/ip/rsa_project_rsa_wrapper_0_0/rsa_project_rsa_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_rsa_wrapper_0_0 || ORIG_REF_NAME==rsa_project_rsa_wrapper_0_0}]

# IP: bd/rsa_project/ip/rsa_project_auto_pc_0/rsa_project_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_auto_pc_0 || ORIG_REF_NAME==rsa_project_auto_pc_0}]

# IP: bd/rsa_project/ip/rsa_project_auto_pc_1/rsa_project_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_auto_pc_1 || ORIG_REF_NAME==rsa_project_auto_pc_1}]

# IP: bd/rsa_project/ip/rsa_project_auto_us_0/rsa_project_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_auto_us_0 || ORIG_REF_NAME==rsa_project_auto_us_0}]

# IP: bd/rsa_project/ip/rsa_project_auto_us_1/rsa_project_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_project_auto_us_1 || ORIG_REF_NAME==rsa_project_auto_us_1}]

# XDC: bd/rsa_project/ip/rsa_project_axi_dma_0_0/rsa_project_axi_dma_0_0_ooc.xdc

# XDC: bd/rsa_project/ip/rsa_project_axi_dma_0_0/rsa_project_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rsa_project_axi_dma_0_0 || ORIG_REF_NAME==rsa_project_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/rsa_project/ip/rsa_project_axi_dma_0_0/rsa_project_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rsa_project_axi_dma_0_0 || ORIG_REF_NAME==rsa_project_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/rsa_project/ip/rsa_project_xbar_0/rsa_project_xbar_0_ooc.xdc

# XDC: bd/rsa_project/ip/rsa_project_xbar_1/rsa_project_xbar_1_ooc.xdc

# XDC: bd/rsa_project/ip/rsa_project_axis_dwidth_converter_0_0/rsa_project_axis_dwidth_converter_0_0_ooc.xdc

# XDC: bd/rsa_project/ip/rsa_project_axis_dwidth_converter_1_0/rsa_project_axis_dwidth_converter_1_0_ooc.xdc

# XDC: bd/rsa_project/ip/rsa_project_rst_processing_system7_0_100M_0/rsa_project_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rsa_project_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==rsa_project_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/rsa_project/ip/rsa_project_rst_processing_system7_0_100M_0/rsa_project_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rsa_project_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==rsa_project_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/rsa_project/ip/rsa_project_rst_processing_system7_0_100M_0/rsa_project_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/rsa_project/ip/rsa_project_processing_system7_0_0/rsa_project_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rsa_project_processing_system7_0_0 || ORIG_REF_NAME==rsa_project_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/rsa_project/ip/rsa_project_auto_pc_0/rsa_project_auto_pc_0_ooc.xdc

# XDC: bd/rsa_project/ip/rsa_project_auto_pc_1/rsa_project_auto_pc_1_ooc.xdc

# XDC: bd/rsa_project/ip/rsa_project_auto_us_0/rsa_project_auto_us_0_ooc.xdc

# XDC: bd/rsa_project/ip/rsa_project_auto_us_0/rsa_project_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rsa_project_auto_us_0 || ORIG_REF_NAME==rsa_project_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/rsa_project/ip/rsa_project_auto_us_1/rsa_project_auto_us_1_ooc.xdc

# XDC: bd/rsa_project/ip/rsa_project_auto_us_1/rsa_project_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rsa_project_auto_us_1 || ORIG_REF_NAME==rsa_project_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/rsa_project/rsa_project_ooc.xdc
