# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config  -ruleid {1}  -id {Synth 8-327}  -new_severity {ERROR} 
set_msg_config  -ruleid {10}  -id {IP_Flow 19-2207}  -new_severity {INFO} 
set_msg_config  -ruleid {11}  -id {Vivado 12-3482}  -new_severity {INFO} 
set_msg_config  -ruleid {2}  -id {Synth 8-3352}  -new_severity {ERROR} 
set_msg_config  -ruleid {3}  -id {Synth 8-5559}  -new_severity {ERROR} 
set_msg_config  -ruleid {4}  -id {Timing 38-282}  -new_severity {WARNING} 
set_msg_config  -ruleid {5}  -id {BD 41-1629}  -new_severity {INFO} 
set_msg_config  -ruleid {6}  -id {BD 41-1343}  -new_severity {INFO} 
set_msg_config  -ruleid {7}  -id {BD_TCL-1000}  -new_severity {INFO} 
set_msg_config  -ruleid {8}  -id {IP_Flow 19-3899}  -new_severity {INFO} 
set_msg_config  -ruleid {9}  -id {IP_Flow 19-3153}  -new_severity {INFO} 
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.cache/wt [current_project]
set_property parent.project_path /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_ipcores
  /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_ipcores
} [current_project]
add_files /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/rsa_project.bd
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_axi_dma_0_0/rsa_project_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_axi_dma_0_0/rsa_project_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_axi_dma_0_0/rsa_project_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_xbar_0/rsa_project_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_xbar_1/rsa_project_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_axis_dwidth_converter_0_0/rsa_project_axis_dwidth_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_axis_dwidth_converter_1_0/rsa_project_axis_dwidth_converter_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_rst_processing_system7_0_100M_0/rsa_project_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_rst_processing_system7_0_100M_0/rsa_project_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_rst_processing_system7_0_100M_0/rsa_project_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_processing_system7_0_0/rsa_project_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_auto_pc_0/rsa_project_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_auto_pc_1/rsa_project_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_auto_us_0/rsa_project_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_auto_us_0/rsa_project_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_auto_us_1/rsa_project_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/ip/rsa_project_auto_us_1/rsa_project_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/rsa_project_ooc.xdc]
set_property is_locked true [get_files /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/bd/rsa_project/rsa_project.bd]

read_verilog -library xil_defaultlib {
  /users/start2016/r0629332/Project-DDP/actual_project/hw_project/src/rtl/adder.v
  /users/start2016/r0629332/Project-DDP/actual_project/hw_project/src/rtl/montgomery.v
  /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/new/exponentiation.v
  /users/start2016/r0629332/Project-DDP/actual_project/hw_project/src/rtl/rsa_wrapper.v
  /users/start2016/r0629332/Project-DDP/actual_project/hw_project/project_hw/project_hw.srcs/sources_1/imports/hdl/rsa_project_wrapper.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc -unmanaged /users/start2016/r0629332/Project-DDP/actual_project/hw_project/tcl/constraints.tcl
set_property used_in_implementation false [get_files /users/start2016/r0629332/Project-DDP/actual_project/hw_project/tcl/constraints.tcl]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top rsa_project_wrapper -part xc7z010clg400-1 -flatten_hierarchy none -directive AlternateRoutability -retiming -control_set_opt_threshold 1


write_checkpoint -force -noxdef rsa_project_wrapper.dcp

catch { report_utilization -file rsa_project_wrapper_utilization_synth.rpt -pb rsa_project_wrapper_utilization_synth.pb }
